## Preliminary

This notebook builds a processed unemployment dataset with Polars LazyFrames.
It reads source data, computes 1/3/5-year changes, merges the features back, reorders columns, and writes the final parquet file.

In [5]:
import polars as pl
from pathlib import Path

import sys


ROOT = Path.cwd().parents[0]

sys.path.append(str(ROOT / "src"))

from fcts import inspect_lazy


DATA_PATH = ROOT / "data"

pulled_data = DATA_PATH / "daioe_scb_years_all_levels.parquet"

processed_data = DATA_PATH / "processed_data.parquet"

## 1. Read the Data

In [6]:
pulled_lf = pl.scan_parquet(pulled_data)

In [7]:
pulled_lf.collect_schema()

Schema([('level', String),
        ('ssyk_code', String),
        ('age', String),
        ('sex', String),
        ('year', Int64),
        ('count', Int64),
        ('occupation', String),
        ('age_group', String),
        ('weight_sum', Int64),
        ('daioe_allapps_avg', Float64),
        ('daioe_stratgames_avg', Float64),
        ('daioe_videogames_avg', Float64),
        ('daioe_imgrec_avg', Float64),
        ('daioe_imgcompr_avg', Float64),
        ('daioe_imggen_avg', Float64),
        ('daioe_readcompr_avg', Float64),
        ('daioe_lngmod_avg', Float64),
        ('daioe_translat_avg', Float64),
        ('daioe_speechrec_avg', Float64),
        ('daioe_genai_avg', Float64),
        ('daioe_allapps_wavg', Float64),
        ('daioe_stratgames_wavg', Float64),
        ('daioe_videogames_wavg', Float64),
        ('daioe_imgrec_wavg', Float64),
        ('daioe_imgcompr_wavg', Float64),
        ('daioe_imggen_wavg', Float64),
        ('daioe_readcompr_wavg', Float64),
        ('daioe_lngmod_wavg', Float64),
        ('daioe_translat_wavg', Float64),
        ('daioe_speechrec_wavg', Float64),
        ('daioe_genai_wavg', Float64),
        ('level_right', String),
        ('pctl_daioe_allapps_avg', Float64),
        ('pctl_daioe_stratgames_avg', Float64),
        ('pctl_daioe_videogames_avg', Float64),
        ('pctl_daioe_imgrec_avg', Float64),
        ('pctl_daioe_imgcompr_avg', Float64),
        ('pctl_daioe_imggen_avg', Float64),
        ('pctl_daioe_readcompr_avg', Float64),
        ('pctl_daioe_lngmod_avg', Float64),
        ('pctl_daioe_translat_avg', Float64),
        ('pctl_daioe_speechrec_avg', Float64),
        ('pctl_daioe_genai_avg', Float64),
        ('pctl_daioe_allapps_wavg', Float64),
        ('pctl_daioe_stratgames_wavg', Float64),
        ('pctl_daioe_videogames_wavg', Float64),
        ('pctl_daioe_imgrec_wavg', Float64),
        ('pctl_daioe_imgcompr_wavg', Float64),
        ('pctl_daioe_imggen_wavg', Float64),
        ('pctl_daioe_readcompr_wavg', Float64),
        ('pctl_daioe_lngmod_wavg', Float64),
        ('pctl_daioe_translat_wavg', Float64),
        ('pctl_daioe_speechrec_wavg', Float64),
        ('pctl_daioe_genai_wavg', Float64),
        ('daioe_allapps_Level_Exposure', Int8),
        ('daioe_stratgames_Level_Exposure', Int8),
        ('daioe_videogames_Level_Exposure', Int8),
        ('daioe_imgrec_Level_Exposure', Int8),
        ('daioe_imgcompr_Level_Exposure', Int8),
        ('daioe_imggen_Level_Exposure', Int8),
        ('daioe_readcompr_Level_Exposure', Int8),
        ('daioe_lngmod_Level_Exposure', Int8),
        ('daioe_translat_Level_Exposure', Int8),
        ('daioe_speechrec_Level_Exposure', Int8),
        ('daioe_genai_Level_Exposure', Int8)])

## 2. Compute the 1-Yr, 3-Yr and 5-Yr Change

Aggregate to unemployment totals by `level`, `ssyk_code`, `age`, `sex`, and `year`, then compute absolute and percent changes over 1, 3, and 5 years using window shifts.

In [8]:
keys = ["level", "ssyk_code", "age", "sex"] 
val = "count"

pulled_with_changes = (
    pulled_lf 
    .group_by([*keys, "year"])
    .agg(pl.col(val).sum().alias("unemp_count"))
    .sort([*keys, "year"])
    .with_columns([
        (pl.col("unemp_count") - pl.col("unemp_count").shift(1).over(keys)).alias("chg_1y"),
        (pl.col("unemp_count") - pl.col("unemp_count").shift(3).over(keys)).alias("chg_3y"),
        (pl.col("unemp_count") - pl.col("unemp_count").shift(5).over(keys)).alias("chg_5y"),

        ((pl.col("unemp_count") / pl.col("unemp_count").shift(1).over(keys) - 1) * 100).alias("pct_chg_1y"),
        ((pl.col("unemp_count") / pl.col("unemp_count").shift(3).over(keys) - 1) * 100).alias("pct_chg_3y"),
        ((pl.col("unemp_count") / pl.col("unemp_count").shift(5).over(keys) - 1) * 100).alias("pct_chg_5y"),
    ])
)

pulled_with_changes.head(20).collect()

shape: (20, 12)
┌───────┬───────────┬────────┬───────┬───┬────────┬────────────┬────────────┬────────────┐
│ level ┆ ssyk_code ┆ age    ┆ sex   ┆ … ┆ chg_5y ┆ pct_chg_1y ┆ pct_chg_3y ┆ pct_chg_5y │
│ ---   ┆ ---       ┆ ---    ┆ ---   ┆   ┆ ---    ┆ ---        ┆ ---        ┆ ---        │
│ str   ┆ str       ┆ str    ┆ str   ┆   ┆ i64    ┆ f64        ┆ f64        ┆ f64        │
╞═══════╪═══════════╪════════╪═══════╪═══╪════════╪════════════╪════════════╪════════════╡
│ SSYK1 ┆ 1         ┆ 065-69 ┆ men   ┆ … ┆ null   ┆ null       ┆ null       ┆ null       │
│ SSYK1 ┆ 1         ┆ 065-69 ┆ men   ┆ … ┆ null   ┆ NaN        ┆ null       ┆ null       │
│ SSYK1 ┆ 1         ┆ 065-69 ┆ men   ┆ … ┆ null   ┆ NaN        ┆ null       ┆ null       │
│ SSYK1 ┆ 1         ┆ 065-69 ┆ men   ┆ … ┆ null   ┆ NaN        ┆ NaN        ┆ null       │
│ SSYK1 ┆ 1         ┆ 065-69 ┆ men   ┆ … ┆ null   ┆ NaN        ┆ NaN        ┆ null       │
│ …     ┆ …         ┆ …      ┆ …     ┆ … ┆ …      ┆ …          ┆ …          ┆ …          │
│ SSYK1 ┆ 1         ┆ 065-69 ┆ women ┆ … ┆ null   ┆ NaN        ┆ NaN        ┆ null       │
│ SSYK1 ┆ 1         ┆ 065-69 ┆ women ┆ … ┆ 0      ┆ NaN        ┆ NaN        ┆ NaN        │
│ SSYK1 ┆ 1         ┆ 065-69 ┆ women ┆ … ┆ 0      ┆ NaN        ┆ NaN        ┆ NaN        │
│ SSYK1 ┆ 1         ┆ 065-69 ┆ women ┆ … ┆ 0      ┆ NaN        ┆ NaN        ┆ NaN        │
│ SSYK1 ┆ 1         ┆ 065-69 ┆ women ┆ … ┆ 0      ┆ NaN        ┆ NaN        ┆ NaN        │
└───────┴───────────┴────────┴───────┴───┴────────┴────────────┴────────────┴────────────┘

In [9]:
inspect_lazy(pulled_with_changes)

Rows: 137,060
Columns: 12

## 3. Merge and write to processed data

Join the engineered change metrics back onto the original table with a left join on the key dimensions, so all original rows are preserved.

In [10]:
join_col = ["year", "level", "ssyk_code", "age", "sex"]

processed_lf = pulled_lf\
    .join(
        pulled_with_changes,
        left_on = join_col,
        right_on = join_col,
        how = "left"
    )

In [11]:
#inspect_lazy(processed_lf)
processed_lf.collect_schema()

Schema([('level', String),
        ('ssyk_code', String),
        ('age', String),
        ('sex', String),
        ('year', Int64),
        ('count', Int64),
        ('occupation', String),
        ('age_group', String),
        ('weight_sum', Int64),
        ('daioe_allapps_avg', Float64),
        ('daioe_stratgames_avg', Float64),
        ('daioe_videogames_avg', Float64),
        ('daioe_imgrec_avg', Float64),
        ('daioe_imgcompr_avg', Float64),
        ('daioe_imggen_avg', Float64),
        ('daioe_readcompr_avg', Float64),
        ('daioe_lngmod_avg', Float64),
        ('daioe_translat_avg', Float64),
        ('daioe_speechrec_avg', Float64),
        ('daioe_genai_avg', Float64),
        ('daioe_allapps_wavg', Float64),
        ('daioe_stratgames_wavg', Float64),
        ('daioe_videogames_wavg', Float64),
        ('daioe_imgrec_wavg', Float64),
        ('daioe_imgcompr_wavg', Float64),
        ('daioe_imggen_wavg', Float64),
        ('daioe_readcompr_wavg', Float64),
        ('daioe_lngmod_wavg', Float64),
        ('daioe_translat_wavg', Float64),
        ('daioe_speechrec_wavg', Float64),
        ('daioe_genai_wavg', Float64),
        ('level_right', String),
        ('pctl_daioe_allapps_avg', Float64),
        ('pctl_daioe_stratgames_avg', Float64),
        ('pctl_daioe_videogames_avg', Float64),
        ('pctl_daioe_imgrec_avg', Float64),
        ('pctl_daioe_imgcompr_avg', Float64),
        ('pctl_daioe_imggen_avg', Float64),
        ('pctl_daioe_readcompr_avg', Float64),
        ('pctl_daioe_lngmod_avg', Float64),
        ('pctl_daioe_translat_avg', Float64),
        ('pctl_daioe_speechrec_avg', Float64),
        ('pctl_daioe_genai_avg', Float64),
        ('pctl_daioe_allapps_wavg', Float64),
        ('pctl_daioe_stratgames_wavg', Float64),
        ('pctl_daioe_videogames_wavg', Float64),
        ('pctl_daioe_imgrec_wavg', Float64),
        ('pctl_daioe_imgcompr_wavg', Float64),
        ('pctl_daioe_imggen_wavg', Float64),
        ('pctl_daioe_readcompr_wavg', Float64),
        ('pctl_daioe_lngmod_wavg', Float64),
        ('pctl_daioe_translat_wavg', Float64),
        ('pctl_daioe_speechrec_wavg', Float64),
        ('pctl_daioe_genai_wavg', Float64),
        ('daioe_allapps_Level_Exposure', Int8),
        ('daioe_stratgames_Level_Exposure', Int8),
        ('daioe_videogames_Level_Exposure', Int8),
        ('daioe_imgrec_Level_Exposure', Int8),
        ('daioe_imgcompr_Level_Exposure', Int8),
        ('daioe_imggen_Level_Exposure', Int8),
        ('daioe_readcompr_Level_Exposure', Int8),
        ('daioe_lngmod_Level_Exposure', Int8),
        ('daioe_translat_Level_Exposure', Int8),
        ('daioe_speechrec_Level_Exposure', Int8),
        ('daioe_genai_Level_Exposure', Int8),
        ('unemp_count', Int64),
        ('chg_1y', Int64),
        ('chg_3y', Int64),
        ('chg_5y', Int64),
        ('pct_chg_1y', Float64),
        ('pct_chg_3y', Float64),
        ('pct_chg_5y', Float64)])

### 3.1 Reorder and Validate Columns

Bring key analytical columns to the front and keep all remaining columns afterward.

A schema snapshot is used to build the final order while keeping all remaining columns.

In [12]:
first_cols = [
    "year",
    "level",
    "ssyk_code",
    "occupation",
    "sex",
    "age",
    "age_group",
    "count",
    "weight_sum",
    "unemp_count",
    "chg_1y",
    "chg_3y",
    "chg_5y",
    "pct_chg_1y",
    "pct_chg_3y",
    "pct_chg_5y"
]

schema_cols = list(processed_lf.collect_schema())

missing_first_cols = [col for col in first_cols if col not in schema_cols]

other_cols = [col for col in schema_cols if col not in first_cols]

processed_lf_reorder_cols =  processed_lf\
    .select(
    first_cols + other_cols
    )\
        .sort(join_col, nulls_last = True, descending = True)

processed_lf_reorder_cols.limit(10).collect()

shape: (10, 72)
┌──────┬───────┬───────────┬─────────────┬───┬─────────────┬─────────────┬────────────┬────────────┐
│ year ┆ level ┆ ssyk_code ┆ occupation  ┆ … ┆ daioe_lngmo ┆ daioe_trans ┆ daioe_spee ┆ daioe_gena │
│ ---  ┆ ---   ┆ ---       ┆ ---         ┆   ┆ d_Level_Exp ┆ lat_Level_E ┆ chrec_Leve ┆ i_Level_Ex │
│ i64  ┆ str   ┆ str       ┆ str         ┆   ┆ osure       ┆ xposure     ┆ l_Exposure ┆ posure     │
│      ┆       ┆           ┆             ┆   ┆ ---         ┆ ---         ┆ ---        ┆ ---        │
│      ┆       ┆           ┆             ┆   ┆ i8          ┆ i8          ┆ i8         ┆ i8         │
╞══════╪═══════╪═══════════╪═════════════╪═══╪═════════════╪═════════════╪════════════╪════════════╡
│ 2024 ┆ SSYK4 ┆ 9629      ┆ Other       ┆ … ┆ 2           ┆ 2           ┆ 2          ┆ 2          │
│      ┆       ┆           ┆ service     ┆   ┆             ┆             ┆            ┆            │
│      ┆       ┆           ┆ workers not ┆   ┆             ┆             ┆            ┆            │
│      ┆       ┆           ┆ else…       ┆   ┆             ┆             ┆            ┆            │
│ 2024 ┆ SSYK4 ┆ 9629      ┆ Other       ┆ … ┆ 2           ┆ 2           ┆ 2          ┆ 2          │
│      ┆       ┆           ┆ service     ┆   ┆             ┆             ┆            ┆            │
│      ┆       ┆           ┆ workers not ┆   ┆             ┆             ┆            ┆            │
│      ┆       ┆           ┆ else…       ┆   ┆             ┆             ┆            ┆            │
│ 2024 ┆ SSYK4 ┆ 9629      ┆ Other       ┆ … ┆ 2           ┆ 2           ┆ 2          ┆ 2          │
│      ┆       ┆           ┆ service     ┆   ┆             ┆             ┆            ┆            │
│      ┆       ┆           ┆ workers not ┆   ┆             ┆             ┆            ┆            │
│      ┆       ┆           ┆ else…       ┆   ┆             ┆             ┆            ┆            │
│ 2024 ┆ SSYK4 ┆ 9629      ┆ Other       ┆ … ┆ 2           ┆ 2           ┆ 2          ┆ 2          │
│      ┆       ┆           ┆ service     ┆   ┆             ┆             ┆            ┆            │
│      ┆       ┆           ┆ workers not ┆   ┆             ┆             ┆            ┆            │
│      ┆       ┆           ┆ else…       ┆   ┆             ┆             ┆            ┆            │
│ 2024 ┆ SSYK4 ┆ 9629      ┆ Other       ┆ … ┆ 2           ┆ 2           ┆ 2          ┆ 2          │
│      ┆       ┆           ┆ service     ┆   ┆             ┆             ┆            ┆            │
│      ┆       ┆           ┆ workers not ┆   ┆             ┆             ┆            ┆            │
│      ┆       ┆           ┆ else…       ┆   ┆             ┆             ┆            ┆            │
│ 2024 ┆ SSYK4 ┆ 9629      ┆ Other       ┆ … ┆ 2           ┆ 2           ┆ 2          ┆ 2          │
│      ┆       ┆           ┆ service     ┆   ┆             ┆             ┆            ┆            │
│      ┆       ┆           ┆ workers not ┆   ┆             ┆             ┆            ┆            │
│      ┆       ┆           ┆ else…       ┆   ┆             ┆             ┆            ┆            │
│ 2024 ┆ SSYK4 ┆ 9629      ┆ Other       ┆ … ┆ 2           ┆ 2           ┆ 2          ┆ 2          │
│      ┆       ┆           ┆ service     ┆   ┆             ┆             ┆            ┆            │
│      ┆       ┆           ┆ workers not ┆   ┆             ┆             ┆            ┆            │
│      ┆       ┆           ┆ else…       ┆   ┆             ┆             ┆            ┆            │
│ 2024 ┆ SSYK4 ┆ 9629      ┆ Other       ┆ … ┆ 2           ┆ 2           ┆ 2          ┆ 2          │
│      ┆       ┆           ┆ service     ┆   ┆             ┆             ┆            ┆            │
│      ┆       ┆           ┆ workers not ┆   ┆             ┆             ┆            ┆            │
│      ┆       ┆           ┆ else…       ┆   ┆             ┆             ┆            ┆            │
│ 2024 ┆ SSYK4 ┆ 9629      ┆ Other       ┆ … ┆ 2           ┆ 2           ┆ 2          ┆ 2          │
│      ┆       ┆           ┆ service     ┆   ┆             ┆             ┆            ┆            │
│      ┆       ┆           ┆ workers not ┆   ┆             ┆             ┆            ┆            │
│      ┆       ┆           ┆ else…       ┆   ┆             ┆             ┆            ┆            │
│ 2024 ┆ SSYK4 ┆ 9629      ┆ Other       ┆ … ┆ 2           ┆ 2           ┆ 2          ┆ 2          │
│      ┆       ┆           ┆ service     ┆   ┆             ┆             ┆            ┆            │
│      ┆       ┆           ┆ workers not ┆   ┆             ┆             ┆            ┆            │
│      ┆       ┆           ┆ else…       ┆   ┆             ┆             ┆            ┆            │
└──────┴───────┴───────────┴─────────────┴───┴─────────────┴─────────────┴────────────┴────────────┘

### 3.2 Export Processed Data

Write the reordered LazyFrame to parquet for downstream app use.

In [13]:
processed_lf_reorder_cols.sink_parquet(processed_data)